List colors = [
  'Absolute Zero',
  'Acid green',
  'Aero',
  'African violet',
  'Air superiority blue',
  'Alice blue',
  'Alizarin',
  'Alloy orange',
  'Almond',
  'Amaranth deep purple',
  'Amaranth pink',
  'Amaranth purple',
  'Amazon',
  'Amber',
  'Amethyst',
  'Android green',
  'Antique brass',
  'Antique bronze',
  'Antique fuchsia',
  'Antique ruby',
  'Antique white',
  'Apricot',
  'Aqua',
  'Aquamarine',
  'Arctic lime',
  'Artichoke green',
  'Arylide yellow',
  'Ash gray',
  'Atomic tangerine',
  'Aureolin',
  'Azure',
  'Azure (X11/web color)',
  'Baby blue',
  'Baby blue eyes',
  'Baby pink',
  'Baby powder',
  'Baker-Miller pink',
  'Banana Mania',
  'Barn red',
  'Battleship grey',
  'Beau blue',
  'Beaver',
  'Beige',
  'B dazzled blue',
  'Big dip o’ruby',
  'Bisque',
  'Bistre',
  'Bistre brown',
  'Bitter lemon',
  'Black',
  'Black bean',
  'Black coral',
  'Black olive',
  'Black Shadows',
  'Blanched almond',
  'Blast-off bronze',
  'Bleu de France',
  'Blizzard blue',
  'Blood red',
  'Blue',
  'Blue (Crayola)',
  'Blue (Munsell)',
  'Blue (NCS)',
  'Blue (Pantone)',
  'Blue (pigment)',
  'Blue bell',
  'Blue-gray (Crayola)',
  'Blue jeans',
  'Blue sapphire',
  'Blue-violet',
  'Blue yonder',
  'Bluetiful',
  'Blush',
  'Bole',
  'Bone',
  'Brick red',
  'Bright lilac',
  'Bright yellow (Crayola)',
  'Bronze',
  'Brown sugar',
  'Bud green',
  'Buff',
  'Burgundy',
  'Burlywood',
  'Burnished brown',
  'Burnt orange',
  'Burnt sienna',
  'Burnt umber',
  'Byzantine',
  'Byzantium',
  'Cadet blue',
  'Cadet grey',
  'Cadmium green',
  'Cadmium orange',
  'Café au lait',
  'Café noir',
  'Cambridge blue',
  'Camel',
  'Cameo pink',
  'Canary',
  'Canary yellow',
  'Candy pink',
  'Cardinal',
  'Caribbean green',
  'Carmine',
  'Carmine (M&P)',
  'Carnation pink',
  'Carnelian',
  'Carolina blue',
  'Carrot orange',
  'Catawba',
  'Cedar Chest',
  'Celadon',
  'Celeste',
  'Cerise',
  'Cerulean',
  'Cerulean blue',
  'Cerulean frost',
  'Cerulean (Crayola)',
  'Champagne',
  'Champagne pink',
  'Charcoal',
  'Charm pink',
  'Chartreuse (web)',
  'Cherry blossom pink',
  'Chestnut',
  'Chili red',
  'China pink',
  'Chinese red',
  'Chinese violet',
  'Chinese yellow',
  'Chocolate (traditional)',
  'Chocolate (web)',
  'Cinereous',
  'Cinnabar',
  'Cinnamon Satin',
  'Citrine',
  'Citron',
  'Claret',
  'Coffee',
  'Columbia Blue',
  'Congo pink',
  'Cool grey',
  'Copper',
  'Copper (Crayola)',
  'Copper penny',
  'Copper red',
  'Copper rose',
  'Coquelicot',
  'Coral',
  'Coral pink',
  'Cordovan',
  'Corn',
  'Cornflower blue',
  'Cornsilk',
  'Cosmic cobalt',
  'Cosmic latte',
  'Coyote brown',
  'Cotton candy',
  'Cream',
  'Crimson',
  'Crimson (UA)',
  'Cultured Pearl',
  'Cyan',
  'Cyan (process)',
  'Cyber grape',
  'Cyber yellow',
  'Cyclamen',
  'Dark brown',
  'Dark byzantium',
  'Dark cyan',
  'Dark electric blue',
  'Dark goldenrod',
  'Dark green (X11)',
  'Dark jungle green',
  'Dark khaki',
  'Dark lava',
  'Dark liver (horses)',
  'Dark magenta',
  'Dark olive green',
  'Dark orange',
  'Dark orchid',
  'Dark purple',
  'Dark red',
  'Dark salmon',
  'Dark sea green',
  'Dark sienna',
  'Dark sky blue',
  'Dark slate blue',
  'Dark slate gray',
  'Dark spring green',
  'Dark turquoise',
  'Dark violet',
  'Davy s grey',
  'Deep cerise',
  'Deep champagne',
  'Deep chestnut',
  'Deep jungle green',
  'Deep pink',
  'Deep saffron',
  'Deep sky blue',
  'Deep Space Sparkle',
  'Deep taupe',
  'Denim',
  'Denim blue',
  'Desert',
  'Desert sand',
  'Dim gray',
  'Dodger blue',
  'Drab dark brown',
  'Duke blue',
  'Dutch white',
  'Ebony',
  'Ecru',
  'Eerie black',
  'Eggplant',
  'Eggshell',
  'Electric lime',
  'Electric purple',
  'Electric violet',
  'Emerald',
  'Eminence',
  'English lavender',
  'English red',
  'English vermillion',
  'English violet',
  'Erin',
  'Eton blue',
  'Fallow',
  'Falu red',
  'Fandango',
  'Fandango pink',
  'Fawn',
  'Fern green',
  'Field drab',
  'Fiery rose',
  'Finn',
  'Firebrick',
  'Fire engine red',
  'Flame',
  'Flax',
  'Flirt',
  'Floral white',
  'Forest green (web)',
  'French beige',
  'French bistre',
  'French blue',
  'French fuchsia',
  'French lilac',
  'French lime',
  'French mauve',
  'French pink',
  'French raspberry',
  'French sky blue',
  'French violet',
  'Frostbite',
  'Fuchsia',
  'Fuchsia (Crayola)',
  'Fulvous',
  'Fuzzy Wuzzy',
];

List compatibility = [
  'Aries',
  'Taurus',
  'Gemini',
  'Cancer',
  'Leo',
  'Virgo',
  'Libra',
  'Scorpio',
  'Sagittarius',
  'Capricorn',
  'Aquarius',
  'Pisces',
];

String getSignDate(String name) {
  if (name == "aries")
    return "MAR 21 - APR 20";
  else if (name == "taurus")
    return "APR 21 - MAY 20";
  else if (name == "gemini")
    return "MAY 21 - JUN 20";
  else if (name == "cancer")
    return "JUN 22 - JUL 22";
  else if (name == "leo")
    return "JUL 23 - AUG 22";
  else if (name == "virgo")
    return "AUG 23 - SEP 22";
  else if (name == "libra")
    return "SEP 23 - OCT 22";
  else if (name == "scorpio")
    return "OCT 23 - NOV 22";
  else if (name == "sagittarius")
    return "NOV 23 - DEC 20";
  else if (name == "capricon")
    return "DEC 22 - JAN 20";
  else if (name == "aquarius")
    return "JAN 21 - FEB 18";
  else if (name == "pisces")
    return "FEB 19 - MAR 20";
  else
    return "";
}

List horoscope = [
  "While you might feel a little restless today, it's crucial to focus your agitation on something positive rather than allowing it to go out of hand. Utilize your motivation and passion to finish a task you've been putting off.",
  "Today is an excellent day to handle practical things. Make sure everything is in order with your money by paying attention to it. You could also want to put an emphasis on your health and wellbeing by exercising and eating right.",
  "Today is all about communication. Make sure you're speaking properly and attentively listening whether you're around friends, family, or coworkers. Also, you might want to concentrate on your creativity and let your mind soar."
      "Today, it's possible that your spending will equal your income. Overall, though, your financial situation will still be strong. To be able to engage in physical exercise, you could feel the need to concentrate on your physical health. Before introducing any new items, it's crucial for entrepreneurs to do a comprehensive market analysis. Be ready for potential arguments with a parent or other respected family member because they could irritate you. If you're planning a lengthy trip, be ready for any detours along the road. All parties involved will gain from the split of an inherited property.",
  "For now, it appears that your financial situation is secure and pleasant. You could be inspired to start a fitness regimen and get exercising. Take breaks and rest when necessary because your present burden may be negatively affecting your physical and mental health. A stress-relieving break will be provided by a calm and loving family life. A road trip is probably going to be pleasurable and easy if you plan on taking one. Also, you might learn about a prospective house addition construction project. Also, the changes you've been yearning for could finally begin to materialise.",
  "You can anticipate some substantial profits today, which will undoubtedly maintain your money account in good shape. Nonetheless, it's crucial to keep in mind to go easy on yourself when exercising and not to strain yourself. You might get some well-deserved credit for the work you've been putting in on a job-related project. Going on holiday and taking a break could be exactly what you need if you're feeling overwhelmed. Make sure to provide a calm and soothing atmosphere at home for individuals wishing to unwind. Keep an eye out for that; you might even get excellent news concerning an ancestral home.",
  "It's crucial to treat your finances carefully today because they can be tight. Before things worsen and become more serious, take care of any unresolved health issues. Your frame of mind at work is ideal for handling negotiations, and you can succeed. It's vital to keep your family informed of your whereabouts in order to prevent any miscommunications. Consider travelling to discover new locations and widen your social network. Negotiations may result in a fantastic price if you're looking to buy a home. To keep in touch with your peers, you could notice that you're drawn to more social activities.",
  "Some of you might do a fantastic job today and leave a lasting impression. It can be best to gently and kindly remind someone to return your money if they forget. You can prevent minor health issues by maintaining a healthy and active lifestyle. You might be asked to plan a family celebration or get-together. Think of organising a trip with a special person or close friend. Keeping an eye out for any opportunities to invest in real estate may result in huge financial advantages.",
  "It's crucial to exercise patience because it's probable that a promised increase or bonus won't materialise straight away. Company owners might notice a change in their favour, which would provide much-needed respite. Nonetheless, some concerns can be stressing you out and weighing heavily on your mind. A family member can show up unannounced and bring joy and excitement. Make sure everything is organised in advance if you're planning a trip to ensure a pleasant experience. An inherited property might provide you with a financial boost and help you out financially. Some people may receive invitations to take part in famous events, which can be a wonderful chance on the social front.",
  "Profitable ventures may not yield a return on investment right now, but the long-term benefits could be game-changing. Keep up the good job; your health is fairly decent. Your business-related suggestions will be well-received and provide you the respect you deserve. Be prepared for some stress because, sadly, there may be some conflict with your partner. Today, you might be embarking on a trip to explore the sites with friends from work or school. The stars indicate that if you've been thinking about buying property, now would be a good moment to act. Although you enjoy interacting with others, beware of those who make you feel bad.",
  "It's crucial to monitor your spending patterns now and cut out any superfluous spending. Keep an ear open because a health-related piece of information could be priceless. Individuals who are in business can anticipate a lucrative transaction. You might be hosting visitors at your house or going to a social event. Traveling might open up new career chances. Maintaining and expanding upon the connections you've already made in your social circle should be your major priority.",
  "An unexpected benefit from a prior investment could provide you with good returns. To keep your health, it's crucial to maintain balance in every aspect of your life. Don't worry too much about it, but you might not feel your most compelling today in business transactions. Instead, concentrate on having fun with your family because you might end up being the centre of attention at a gathering. If you intend to go to see loved ones, be prepared for an exciting and joyful journey. Moreover, you might hear excellent news about a house you've had your eye on — it might finally be yours!",
  "It may be challenging to select the best investment strategies. If you want to stay in shape, a chosen diet might become your guiding principle. At work, someone might rile you up and make you angry. Your property is probably going to benefit from your imagination and attention to detail. You can get all enthusiastic when a visitor from another country arrives. For those who are about to make a reservation for a flat or flat, today is a lucky day. You might receive an invitation to a social event or a party.",
  "Today's horoscope suggests that you may receive financial advice from someone knowledgeable in the field, which will help stabilize your monetary front. A new health initiative you have taken up will yield positive results. However, you may struggle to focus on your work, which could lead to delays or errors. On the family front, you will find a peaceful environment that allows you to pursue your interests. There are indications of a property deal materializing for those seeking to purchase a house. Those undertaking a long journey are likely to make good progress. Your efforts to improve your quality of life will require intense focus and determination.",
  "Improved earnings will enable you to afford some luxury items that you have been eyeing for a while. It is advisable to switch to a healthier diet at this time. A challenging assignment may come your way on the professional front, which will require you to consider all your options before making a decision. Your spouse will be responsive and accommodating to your needs. An extended vacation may become dull, and a good bargain is foreseen on the property front. It is not necessary to reveal your innermost thoughts to someone, even if they are your well-wisher.",
  "Your desire to purchase something expensive will be fulfilled, as you have the necessary funds. A healthy diet is essential, and those who have taken up an exercise regimen will see positive results. Regaining control on the professional front may prove challenging, and you may face blame on the home front, causing you to become upset. Adequate preparation is recommended for those embarking on a journey. You may become the owner of a property that you have invested in, and your social initiatives are likely to be appreciated by all.",
  "An outstanding amount of money owed to you may be released soon. Positive results are expected for those who have taken up regular exercise. Some difficulties may be faced in regaining control on the professional front, but it will lead to fruitful results. A family gathering is in the offing, which promises much excitement. Those who are craving a break can opt for an exotic vacation. This is an excellent time to book an apartment or a flat. Your helpfulness is likely to add to your prestige and reputation on the social front.",
  "Financially, you are better off than what you may lead others to believe. You are likely to remain health-conscious with the aim of becoming entirely fit. Your previous efforts on the professional front may come to fruition now. A family gathering can get you entirely involved and prey on your time too. A change of scenery is likely for those planning a vacation. Some builders may start thinking in terms of a township soon. Your social circle is set to expand.",
  "You are likely to take on more work at your job than you can comfortably handle on the professional front. You may face the possibility of losing money invested in a dubious scheme. Fitness can become an issue for those who do not subscribe to an active lifestyle. You should check your mood swings, as they may upset others in the family. Those embarking on an overseas vacation can expect an exciting time. Some of you are likely to become the proud owner of a property. Your well-wishers are likely to add to your prestige and reputation on the social front.",
  "You are likely to experience a positive phase in your professional life. It is best to start saving now, as it may become difficult later. Health remains satisfactory, but minor problems cannot be ruled out. The marriage of someone close in the family is likely to get fixed. Plan your vacation well to remain within the budget. A decision on the property front will be in your favor, and an invitation to a party or wedding can be received.",
  "You will have the means to indulge yourself and buy something you have been wanting. Focusing on your dietary intake will be in your interest. Things will move at a fast but",
  "You will have the means to indulge yourself and buy something you have been wanting. Focusing on your dietary intake will be in your interest. Things will move at a fast but",
  "Students have the potential to excel academically today. Businesspeople should actively seek out potential partnerships. Seek the blessings of your elders before embarking on new adventures. Pay attention to the needs of your family to keep the peace at home. Avoid pushing your body too hard and get proper sleep. Proper planning and preparation can lead to a successful trip.",
  "Maintain financial stability by controlling your spending. Recent graduates may have new job opportunities. Pay down mortgages on your real estate to improve your financial situation. Your eagerness to learn and improve will earn you respect in the workplace. Take care of your physical health by listening to your body's signals. Travelling to a new location can be rewarding. Consider buying a home or apartment.",
  "Business owners may find new ways to expand their reach. Spend quality time with loved ones to strengthen familial bonds. Use logic to make important decisions and avoid delegating tasks. Travel can be rewarding but be prepared for the unexpected. Regular meditation can lead to profound calm and contentment. A positive academic outcome is possible.",
  "Contribute towards shared financial goals. Give children room to learn from their mistakes. Disputes over ancestral property may arise. Leadership roles in your field of expertise may be offered. Academic efforts may come to fruition. Host someone who admires you. Control spending to avoid a financial crisis.",
  "Don't rush important decisions that could jeopardize relationships at home. Professional success is tied to your core competencies and skills. Take care of your physical health. Proper planning is key to a successful trip. Diversify plans to succeed at work. Be cautious with property deals and rental agreements. Good health boosts vitality and energy.",
  "It appears that today could be a favorable day for signing contracts or pursuing business deals. There may also be opportunities to invest in the property market. It is important to prioritize the health of your loved ones, and students may have a chance to win a competition. Colleagues could lend their support in completing work projects, and it may be a good time to focus on improving your mental well-being. Some may enjoy a fun outing today.",
  "If you are looking for passive income ideas or interested in buying or selling property, luck may be on your side. Positive changes may bring harmony to your home life, but newcomers may want to be cautious when making career decisions. A detoxification diet could be beneficial for some, and travel may offer a chance to unwind and explore new cultures.",
  "Be mindful of balancing your expenses and income. Kids may impress with academic achievements, and it's important to stay attentive at work. Traveling with loved ones could reduce stress and offer a chance to relax. Homemakers may want to indulge in a beauty treatment, and some may achieve their dream of buying a property.",
  "It is advisable to avoid get-rich-quick schemes and lending large sums of money. Women may feel inclined to indulge in some shopping and self-care, and real estate developers may find today to be lucky. Those taking competitive exams could do well, and academic efforts may be rewarded. However, it may be wise to avoid unhygienic food as health concerns may arise.",
  "It would be a great idea to get in touch with old pals today and organise a trip together. With your friends, you can find yourself engaging in outdoor pursuits like swimming and surfing. You may enjoy spending time with your siblings or relatives and have a good family life as well. But today, it's critical to exercise financial restraint and stay away from high-risk ventures.",
  "Things are improving at work, and you might be rewarded for your efforts. If you own property, you might be able to find good tenants. To preserve their health, women may find it beneficial to attempt yoga, meditation, or physical activity. Academically, students might make steady improvement.",
  "To escape the monotony if you're feeling trapped in a rut, consider organising a trip with old pals. You might also think about getting a new house, but you need to proceed carefully. Homemakers who want to get in shape might find it helpful to sign up for dance or fitness lessons. Although there may be financial difficulties, today is a good day for authors and marketers.",
  "If you're thinking about doing any house improvements or repairs, it might keep you busy for a while. It's important to provide your family with assistance if someone is feeling under the weather. Work visits might prove profitable, and you might score some great deals. You might succeed in whatever goal you set for today thanks to your enthusiasm and outlook.",
  "If you're a student, you might have academic success that is unheard of. Avoid purchasing real estate right now, and be ready for any monetary problems that may occur. Generally, your life today is predicted to continue steadily."
];
